// <auto-generated />
using DB.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DB.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DB.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AC")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            AC = 11,
                            AttackModifier = 7,
                            AttackPerRound = 1,
                            Damage = "2d8",
                            DamageModifier = 5,
                            HP = 45,
                            Name = "Rhinoceros"
                        },
                        new
                        {
                            Id = 6,
                            AC = 12,
                            AttackModifier = 3,
                            AttackPerRound = 4,
                            Damage = "1d4",
                            DamageModifier = 2,
                            HP = 40,
                            Name = "Mage"
                        },
                        new
                        {
                            Id = 7,
                            AC = 12,
                            AttackModifier = 0,
                            AttackPerRound = 1,
                            Damage = "1d1",
                            DamageModifier = 0,
                            HP = 2,
                            Name = "Cat"
                        },
                        new
                        {
                            Id = 8,
                            AC = 12,
                            AttackModifier = 3,
                            AttackPerRound = 1,
                            Damage = "1d8",
                            DamageModifier = 1,
                            HP = 32,
                            Name = "Ice Frog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
